*------------------------------------------------------------*;
* Metadata Changes;
*------------------------------------------------------------*;
if upcase(NAME) = "ACCEPTEDCMP1" then ROLE="REJECTED";
if upcase(NAME) = "ACCEPTEDCMP2" then ROLE="REJECTED";
if upcase(NAME) = "ACCEPTEDCMP3" then ROLE="REJECTED";
if upcase(NAME) = "ACCEPTEDCMP4" then ROLE="REJECTED";
if upcase(NAME) = "ACCEPTEDCMP5" then ROLE="REJECTED";
if upcase(NAME) = "AGE" then ROLE="REJECTED";
if upcase(NAME) = "COMPLAIN" then ROLE="REJECTED";
if upcase(NAME) = "DT_CUSTOMER" then ROLE="REJECTED";
if upcase(NAME) = "EDUCATION" then ROLE="REJECTED";
if upcase(NAME) = "HIGHEREDUCATION" then ROLE="REJECTED";
if upcase(NAME) = "HIGHEREDUCATION" then delete;
if upcase(NAME) = "HIGHEREDUCATIONBINARY" then ROLE="REJECTED";
if upcase(NAME) = "INCOME" then ROLE="REJECTED";
if upcase(NAME) = "KIDHOME" then ROLE="REJECTED";
if upcase(NAME) = "MNTFISHPRODUCTS" then ROLE="REJECTED";
if upcase(NAME) = "MNTFRUITS" then ROLE="REJECTED";
if upcase(NAME) = "MNTGOLDPRODS" then ROLE="REJECTED";
if upcase(NAME) = "MNTSWEETPRODUCTS" then ROLE="REJECTED";
if upcase(NAME) = "MNTWINES" then ROLE="REJECTED";
if upcase(NAME) = "MONTHSASCUSTOMER" then ROLE="REJECTED";
if upcase(NAME) = "NUMDISTPURCHASES" then ROLE="REJECTED";
if upcase(NAME) = "NUMSTOREPURCHASES" then ROLE="REJECTED";
if upcase(NAME) = "NUMWEBPURCHASES" then ROLE="REJECTED";
if upcase(NAME) = "RFMSTAT" then ROLE="REJECTED";
if upcase(NAME) = "RMNTFRQ" then ROLE="REJECTED";
if upcase(NAME) = "TEENHOME" then ROLE="REJECTED";
if upcase(NAME) = "YEAR_BIRTH" then ROLE="REJECTED";
