if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'ACCEPTEDCMPTOTAL'
'FRQ'
'MARITAL_STATUS'
'MNT'
'MNTMEATPRODUCTS'
'NUMCATALOGPURCHASES'
'NUMDEALSPURCHASES'
'NUMWEBVISITSMONTH'
'RECENCY'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg11: Rejected using stepwise selection";
end;
end;
