*------------------------------------------------------------*;
* Ensmbl53: Voting to produce predicted target;
*------------------------------------------------------------*;
array Ensmbl53_post{2} _temporary_;
array Ensmbl53_count{2} _temporary_;
array Ensmbl53_level{2} $32 _temporary_ (
"1"
"0"
);
do i=1 to 2;
Ensmbl53_post{i} = 0;
Ensmbl53_count{i} = 0;
end;
if AutoNeural30_I_DepVar = Ensmbl53_level{1} then do;
Ensmbl53_count{1} + 1;
Ensmbl53_post{1}=Ensmbl53_post{1}+ AutoNeural30_P_DepVar1;
end;
if AutoNeural31_I_DepVar = Ensmbl53_level{1} then do;
Ensmbl53_count{1} + 1;
Ensmbl53_post{1}=Ensmbl53_post{1}+ AutoNeural31_P_DepVar1;
end;
if AutoNeural32_I_DepVar = Ensmbl53_level{1} then do;
Ensmbl53_count{1} + 1;
Ensmbl53_post{1}=Ensmbl53_post{1}+ AutoNeural32_P_DepVar1;
end;
if AutoNeural33_I_DepVar = Ensmbl53_level{1} then do;
Ensmbl53_count{1} + 1;
Ensmbl53_post{1}=Ensmbl53_post{1}+ AutoNeural33_P_DepVar1;
end;
if AutoNeural27_I_DepVar = Ensmbl53_level{1} then do;
Ensmbl53_count{1} + 1;
Ensmbl53_post{1}=Ensmbl53_post{1}+ AutoNeural27_P_DepVar1;
end;
if AutoNeural28_I_DepVar = Ensmbl53_level{1} then do;
Ensmbl53_count{1} + 1;
Ensmbl53_post{1}=Ensmbl53_post{1}+ AutoNeural28_P_DepVar1;
end;
if AutoNeural29_I_DepVar = Ensmbl53_level{1} then do;
Ensmbl53_count{1} + 1;
Ensmbl53_post{1}=Ensmbl53_post{1}+ AutoNeural29_P_DepVar1;
end;
if AutoNeural30_I_DepVar = Ensmbl53_level{2} then do;
Ensmbl53_count{2} + 1;
Ensmbl53_post{2}=Ensmbl53_post{2}+ AutoNeural30_P_DepVar0;
end;
if AutoNeural31_I_DepVar = Ensmbl53_level{2} then do;
Ensmbl53_count{2} + 1;
Ensmbl53_post{2}=Ensmbl53_post{2}+ AutoNeural31_P_DepVar0;
end;
if AutoNeural32_I_DepVar = Ensmbl53_level{2} then do;
Ensmbl53_count{2} + 1;
Ensmbl53_post{2}=Ensmbl53_post{2}+ AutoNeural32_P_DepVar0;
end;
if AutoNeural33_I_DepVar = Ensmbl53_level{2} then do;
Ensmbl53_count{2} + 1;
Ensmbl53_post{2}=Ensmbl53_post{2}+ AutoNeural33_P_DepVar0;
end;
if AutoNeural27_I_DepVar = Ensmbl53_level{2} then do;
Ensmbl53_count{2} + 1;
Ensmbl53_post{2}=Ensmbl53_post{2}+ AutoNeural27_P_DepVar0;
end;
if AutoNeural28_I_DepVar = Ensmbl53_level{2} then do;
Ensmbl53_count{2} + 1;
Ensmbl53_post{2}=Ensmbl53_post{2}+ AutoNeural28_P_DepVar0;
end;
if AutoNeural29_I_DepVar = Ensmbl53_level{2} then do;
Ensmbl53_count{2} + 1;
Ensmbl53_post{2}=Ensmbl53_post{2}+ AutoNeural29_P_DepVar0;
end;
*------------------------------------------------------------*;
* Ensmbl53: Determine Into Variable;
*------------------------------------------------------------*;
length I_DepVar $32;
drop i vote_count vote_post;
vote_count = max(
Ensmbl53_count{1} ,
Ensmbl53_count{2}
);
do i=1 to 2;
if Ensmbl53_count{i}=vote_count and Ensmbl53_post{i}>vote_post then do;
I_DepVar = Ensmbl53_level{i};
vote_post = Ensmbl53_count{i};
end;
end;
*------------------------------------------------------------*;
* Ensmbl53: Compute posterior vars using models predicting the chosen level;
*------------------------------------------------------------*;
P_DepVar1 = 0;
P_DepVar0 = 0;
if I_DepVar = AutoNeural30_I_DepVar then do;
P_DEPVAR1 = P_DEPVAR1 + AutoNeural30_P_DepVar1;
P_DEPVAR0 = P_DEPVAR0 + AutoNeural30_P_DepVar0;
end;
if I_DepVar = AutoNeural31_I_DepVar then do;
P_DEPVAR1 = P_DEPVAR1 + AutoNeural31_P_DepVar1;
P_DEPVAR0 = P_DEPVAR0 + AutoNeural31_P_DepVar0;
end;
if I_DepVar = AutoNeural32_I_DepVar then do;
P_DEPVAR1 = P_DEPVAR1 + AutoNeural32_P_DepVar1;
P_DEPVAR0 = P_DEPVAR0 + AutoNeural32_P_DepVar0;
end;
if I_DepVar = AutoNeural33_I_DepVar then do;
P_DEPVAR1 = P_DEPVAR1 + AutoNeural33_P_DepVar1;
P_DEPVAR0 = P_DEPVAR0 + AutoNeural33_P_DepVar0;
end;
if I_DepVar = AutoNeural27_I_DepVar then do;
P_DEPVAR1 = P_DEPVAR1 + AutoNeural27_P_DepVar1;
P_DEPVAR0 = P_DEPVAR0 + AutoNeural27_P_DepVar0;
end;
if I_DepVar = AutoNeural28_I_DepVar then do;
P_DEPVAR1 = P_DEPVAR1 + AutoNeural28_P_DepVar1;
P_DEPVAR0 = P_DEPVAR0 + AutoNeural28_P_DepVar0;
end;
if I_DepVar = AutoNeural29_I_DepVar then do;
P_DEPVAR1 = P_DEPVAR1 + AutoNeural29_P_DepVar1;
P_DEPVAR0 = P_DEPVAR0 + AutoNeural29_P_DepVar0;
end;
* Ensmbl53: Averaging posterior;
P_DepVar1 = P_DepVar1/vote_count;
P_DepVar0 = P_DepVar0/vote_count;
*------------------------------------------------------------*;
* Ensmbl53: Producing Unformatted variable;
*------------------------------------------------------------*;
label U_DepVar = "Unnormalized Into: DepVar";
if I_DepVar = '1' then U_DepVar = 1;
else
if I_DepVar = '0' then U_DepVar = 0;
*------------------------------------------------------------*;
* Ensmbl53: Computing _WARN_ Variable;
*------------------------------------------------------------*;
length _WARN_ $4;
label _WARN_ = 'Warnings';
_WARN_ = '';
if index(AUTONEURAL30_WARN_, 'M') and ^index(_WARN_, 'M') then substr(_WARN_, 1, 1) ='M';
if index(AUTONEURAL30_WARN_, 'U') and ^index(_WARN_, 'U') then substr(_WARN_, 2, 1) ='U';
if index(AUTONEURAL30_WARN_, 'P') and ^index(_WARN_, 'P') then substr(_WARN_, 3, 1) ='P';
if index(AUTONEURAL30_WARN_, 'C') and ^index(_WARN_, 'C') then substr(_WARN_, 4, 1) ='C';
if index(AUTONEURAL31_WARN_, 'M') and ^index(_WARN_, 'M') then substr(_WARN_, 1, 1) ='M';
if index(AUTONEURAL31_WARN_, 'U') and ^index(_WARN_, 'U') then substr(_WARN_, 2, 1) ='U';
if index(AUTONEURAL31_WARN_, 'P') and ^index(_WARN_, 'P') then substr(_WARN_, 3, 1) ='P';
if index(AUTONEURAL31_WARN_, 'C') and ^index(_WARN_, 'C') then substr(_WARN_, 4, 1) ='C';
if index(AUTONEURAL32_WARN_, 'M') and ^index(_WARN_, 'M') then substr(_WARN_, 1, 1) ='M';
if index(AUTONEURAL32_WARN_, 'U') and ^index(_WARN_, 'U') then substr(_WARN_, 2, 1) ='U';
if index(AUTONEURAL32_WARN_, 'P') and ^index(_WARN_, 'P') then substr(_WARN_, 3, 1) ='P';
if index(AUTONEURAL32_WARN_, 'C') and ^index(_WARN_, 'C') then substr(_WARN_, 4, 1) ='C';
if index(AUTONEURAL33_WARN_, 'M') and ^index(_WARN_, 'M') then substr(_WARN_, 1, 1) ='M';
if index(AUTONEURAL33_WARN_, 'U') and ^index(_WARN_, 'U') then substr(_WARN_, 2, 1) ='U';
if index(AUTONEURAL33_WARN_, 'P') and ^index(_WARN_, 'P') then substr(_WARN_, 3, 1) ='P';
if index(AUTONEURAL33_WARN_, 'C') and ^index(_WARN_, 'C') then substr(_WARN_, 4, 1) ='C';
if index(AUTONEURAL27_WARN_, 'M') and ^index(_WARN_, 'M') then substr(_WARN_, 1, 1) ='M';
if index(AUTONEURAL27_WARN_, 'U') and ^index(_WARN_, 'U') then substr(_WARN_, 2, 1) ='U';
if index(AUTONEURAL27_WARN_, 'P') and ^index(_WARN_, 'P') then substr(_WARN_, 3, 1) ='P';
if index(AUTONEURAL27_WARN_, 'C') and ^index(_WARN_, 'C') then substr(_WARN_, 4, 1) ='C';
if index(AUTONEURAL28_WARN_, 'M') and ^index(_WARN_, 'M') then substr(_WARN_, 1, 1) ='M';
if index(AUTONEURAL28_WARN_, 'U') and ^index(_WARN_, 'U') then substr(_WARN_, 2, 1) ='U';
if index(AUTONEURAL28_WARN_, 'P') and ^index(_WARN_, 'P') then substr(_WARN_, 3, 1) ='P';
if index(AUTONEURAL28_WARN_, 'C') and ^index(_WARN_, 'C') then substr(_WARN_, 4, 1) ='C';
if index(AUTONEURAL29_WARN_, 'M') and ^index(_WARN_, 'M') then substr(_WARN_, 1, 1) ='M';
if index(AUTONEURAL29_WARN_, 'U') and ^index(_WARN_, 'U') then substr(_WARN_, 2, 1) ='U';
if index(AUTONEURAL29_WARN_, 'P') and ^index(_WARN_, 'P') then substr(_WARN_, 3, 1) ='P';
if index(AUTONEURAL29_WARN_, 'C') and ^index(_WARN_, 'C') then substr(_WARN_, 4, 1) ='C';
