*------------------------------------------------------------*;
* Metadata Changes;
*------------------------------------------------------------*;
if upcase(NAME) = "AGE" then ROLE="REJECTED";
if upcase(NAME) = "AGE" then delete;
if upcase(NAME) = "AGE_EXMPL2" then ROLE="REJECTED";
if upcase(NAME) = "AGE_EXMPL2" then delete;
if upcase(NAME) = "COSTPERCONTACT" then ROLE="REJECTED";
if upcase(NAME) = "COSTPERCONTACT" then delete;
if upcase(NAME) = "DT_CUSTOMER" then ROLE="REJECTED";
if upcase(NAME) = "DT_CUSTOMER" then delete;
if upcase(NAME) = "EDUCATION" then ROLE="REJECTED";
if upcase(NAME) = "EDUCATION" then delete;
if upcase(NAME) = "FRQ" then ROLE="REJECTED";
if upcase(NAME) = "FRQ" then delete;
if upcase(NAME) = "GENDER" then ROLE="REJECTED";
if upcase(NAME) = "GENDER" then delete;
if upcase(NAME) = "HIGHEREDUCATION" then ROLE="REJECTED";
if upcase(NAME) = "HIGHEREDUCATION" then delete;
if upcase(NAME) = "INCOME" then ROLE="REJECTED";
if upcase(NAME) = "INCOME" then delete;
if upcase(NAME) = "KITCHEN" then ROLE="REJECTED";
if upcase(NAME) = "KITCHEN" then delete;
if upcase(NAME) = "MONTHSASCUSTOMER" then ROLE="REJECTED";
if upcase(NAME) = "MONTHSASCUSTOMER" then delete;
if upcase(NAME) = "NETPURCHASE" then ROLE="REJECTED";
if upcase(NAME) = "NETPURCHASE" then delete;
if upcase(NAME) = "RMNTFRQ" then ROLE="REJECTED";
if upcase(NAME) = "RMNTFRQ" then delete;
if upcase(NAME) = "RMNTFRQ_EXMPL2" then ROLE="REJECTED";
if upcase(NAME) = "RMNTFRQ_EXMPL2" then delete;
if upcase(NAME) = "REVENUEPERPOSITIVEANSWER" then ROLE="REJECTED";
if upcase(NAME) = "REVENUEPERPOSITIVEANSWER" then delete;
if upcase(NAME) = "YEAR_BIRTH" then ROLE="REJECTED";
if upcase(NAME) = "YEAR_BIRTH" then delete;
