*------------------------------------------------------------*;
* Variable Attributes for DATA;
*------------------------------------------------------------*;
if upcase(NAME) = "AGE" then NEWROLE="REJECTED";
if upcase(NAME) = "AGE" then HIDE="Y";
if upcase(NAME) = "AGE_EXMPL2" then NEWROLE="REJECTED";
if upcase(NAME) = "AGE_EXMPL2" then HIDE="Y";
if upcase(NAME) = "COSTPERCONTACT" then NEWROLE="REJECTED";
if upcase(NAME) = "COSTPERCONTACT" then HIDE="Y";
if upcase(NAME) = "DT_CUSTOMER" then NEWROLE="REJECTED";
if upcase(NAME) = "DT_CUSTOMER" then HIDE="Y";
if upcase(NAME) = "EDUCATION" then NEWROLE="REJECTED";
if upcase(NAME) = "EDUCATION" then HIDE="Y";
if upcase(NAME) = "FRQ" then NEWROLE="REJECTED";
if upcase(NAME) = "FRQ" then HIDE="Y";
if upcase(NAME) = "GENDER" then NEWROLE="REJECTED";
if upcase(NAME) = "GENDER" then HIDE="Y";
if upcase(NAME) = "HIGHEREDUCATION" then NEWROLE="REJECTED";
if upcase(NAME) = "HIGHEREDUCATION" then HIDE="Y";
if upcase(NAME) = "INCOME" then NEWROLE="REJECTED";
if upcase(NAME) = "INCOME" then HIDE="Y";
if upcase(NAME) = "KITCHEN" then NEWROLE="REJECTED";
if upcase(NAME) = "KITCHEN" then HIDE="Y";
if upcase(NAME) = "MONTHSASCUSTOMER" then NEWROLE="REJECTED";
if upcase(NAME) = "MONTHSASCUSTOMER" then HIDE="Y";
if upcase(NAME) = "NETPURCHASE" then NEWROLE="REJECTED";
if upcase(NAME) = "NETPURCHASE" then HIDE="Y";
if upcase(NAME) = "RMNTFRQ" then NEWROLE="REJECTED";
if upcase(NAME) = "RMNTFRQ" then HIDE="Y";
if upcase(NAME) = "RMNTFRQ_EXMPL2" then NEWROLE="REJECTED";
if upcase(NAME) = "RMNTFRQ_EXMPL2" then HIDE="Y";
if upcase(NAME) = "REVENUEPERPOSITIVEANSWER" then NEWROLE="REJECTED";
if upcase(NAME) = "REVENUEPERPOSITIVEANSWER" then HIDE="Y";
if upcase(NAME) = "YEAR_BIRTH" then NEWROLE="REJECTED";
if upcase(NAME) = "YEAR_BIRTH" then HIDE="Y";
