if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'ACCEPTEDCMP5'
'ACCEPTEDCMPTOTAL'
'MARITAL_STATUS'
'MNT'
'MNTGOLDPRODS'
'MNTMEATPRODUCTS'
'NUMCATALOGPURCHASES'
'NUMDEALSPURCHASES'
'NUMDISTPURCHASES'
'NUMSTOREPURCHASES'
'NUMWEBVISITSMONTH'
'RFMSTAT'
'RECENCY'
'TEENHOME'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg: Rejected using stepwise selection";
end;
end;
