*------------------------------------------------------------*;
* Ensmbl56: Voting to produce predicted target;
*------------------------------------------------------------*;
array Ensmbl56_post{2} _temporary_;
array Ensmbl56_count{2} _temporary_;
array Ensmbl56_level{2} $32 _temporary_ (
"1"
"0"
);
do i=1 to 2;
Ensmbl56_post{i} = 0;
Ensmbl56_count{i} = 0;
end;
if AutoNeural36_I_DepVar = Ensmbl56_level{1} then do;
Ensmbl56_count{1} + 1;
Ensmbl56_post{1}=Ensmbl56_post{1}+ AutoNeural36_P_DepVar1;
end;
if AutoNeural35_I_DepVar = Ensmbl56_level{1} then do;
Ensmbl56_count{1} + 1;
Ensmbl56_post{1}=Ensmbl56_post{1}+ AutoNeural35_P_DepVar1;
end;
if AutoNeural34_I_DepVar = Ensmbl56_level{1} then do;
Ensmbl56_count{1} + 1;
Ensmbl56_post{1}=Ensmbl56_post{1}+ AutoNeural34_P_DepVar1;
end;
if AutoNeural40_I_DepVar = Ensmbl56_level{1} then do;
Ensmbl56_count{1} + 1;
Ensmbl56_post{1}=Ensmbl56_post{1}+ AutoNeural40_P_DepVar1;
end;
if AutoNeural39_I_DepVar = Ensmbl56_level{1} then do;
Ensmbl56_count{1} + 1;
Ensmbl56_post{1}=Ensmbl56_post{1}+ AutoNeural39_P_DepVar1;
end;
if AutoNeural38_I_DepVar = Ensmbl56_level{1} then do;
Ensmbl56_count{1} + 1;
Ensmbl56_post{1}=Ensmbl56_post{1}+ AutoNeural38_P_DepVar1;
end;
if AutoNeural37_I_DepVar = Ensmbl56_level{1} then do;
Ensmbl56_count{1} + 1;
Ensmbl56_post{1}=Ensmbl56_post{1}+ AutoNeural37_P_DepVar1;
end;
if AutoNeural36_I_DepVar = Ensmbl56_level{2} then do;
Ensmbl56_count{2} + 1;
Ensmbl56_post{2}=Ensmbl56_post{2}+ AutoNeural36_P_DepVar0;
end;
if AutoNeural35_I_DepVar = Ensmbl56_level{2} then do;
Ensmbl56_count{2} + 1;
Ensmbl56_post{2}=Ensmbl56_post{2}+ AutoNeural35_P_DepVar0;
end;
if AutoNeural34_I_DepVar = Ensmbl56_level{2} then do;
Ensmbl56_count{2} + 1;
Ensmbl56_post{2}=Ensmbl56_post{2}+ AutoNeural34_P_DepVar0;
end;
if AutoNeural40_I_DepVar = Ensmbl56_level{2} then do;
Ensmbl56_count{2} + 1;
Ensmbl56_post{2}=Ensmbl56_post{2}+ AutoNeural40_P_DepVar0;
end;
if AutoNeural39_I_DepVar = Ensmbl56_level{2} then do;
Ensmbl56_count{2} + 1;
Ensmbl56_post{2}=Ensmbl56_post{2}+ AutoNeural39_P_DepVar0;
end;
if AutoNeural38_I_DepVar = Ensmbl56_level{2} then do;
Ensmbl56_count{2} + 1;
Ensmbl56_post{2}=Ensmbl56_post{2}+ AutoNeural38_P_DepVar0;
end;
if AutoNeural37_I_DepVar = Ensmbl56_level{2} then do;
Ensmbl56_count{2} + 1;
Ensmbl56_post{2}=Ensmbl56_post{2}+ AutoNeural37_P_DepVar0;
end;
*------------------------------------------------------------*;
* Ensmbl56: Determine Into Variable;
*------------------------------------------------------------*;
length I_DepVar $32;
drop i vote_count vote_post;
vote_count = max(
Ensmbl56_count{1} ,
Ensmbl56_count{2}
);
do i=1 to 2;
if Ensmbl56_count{i}=vote_count and Ensmbl56_post{i}>vote_post then do;
I_DepVar = Ensmbl56_level{i};
vote_post = Ensmbl56_count{i};
end;
end;
*------------------------------------------------------------*;
* Ensmbl56: Compute posterior vars using models predicting the chosen level;
*------------------------------------------------------------*;
P_DepVar1 = 0;
P_DepVar0 = 0;
if I_DepVar = AutoNeural36_I_DepVar then do;
P_DEPVAR1 = P_DEPVAR1 + AutoNeural36_P_DepVar1;
P_DEPVAR0 = P_DEPVAR0 + AutoNeural36_P_DepVar0;
end;
if I_DepVar = AutoNeural35_I_DepVar then do;
P_DEPVAR1 = P_DEPVAR1 + AutoNeural35_P_DepVar1;
P_DEPVAR0 = P_DEPVAR0 + AutoNeural35_P_DepVar0;
end;
if I_DepVar = AutoNeural34_I_DepVar then do;
P_DEPVAR1 = P_DEPVAR1 + AutoNeural34_P_DepVar1;
P_DEPVAR0 = P_DEPVAR0 + AutoNeural34_P_DepVar0;
end;
if I_DepVar = AutoNeural40_I_DepVar then do;
P_DEPVAR1 = P_DEPVAR1 + AutoNeural40_P_DepVar1;
P_DEPVAR0 = P_DEPVAR0 + AutoNeural40_P_DepVar0;
end;
if I_DepVar = AutoNeural39_I_DepVar then do;
P_DEPVAR1 = P_DEPVAR1 + AutoNeural39_P_DepVar1;
P_DEPVAR0 = P_DEPVAR0 + AutoNeural39_P_DepVar0;
end;
if I_DepVar = AutoNeural38_I_DepVar then do;
P_DEPVAR1 = P_DEPVAR1 + AutoNeural38_P_DepVar1;
P_DEPVAR0 = P_DEPVAR0 + AutoNeural38_P_DepVar0;
end;
if I_DepVar = AutoNeural37_I_DepVar then do;
P_DEPVAR1 = P_DEPVAR1 + AutoNeural37_P_DepVar1;
P_DEPVAR0 = P_DEPVAR0 + AutoNeural37_P_DepVar0;
end;
* Ensmbl56: Averaging posterior;
P_DepVar1 = P_DepVar1/vote_count;
P_DepVar0 = P_DepVar0/vote_count;
*------------------------------------------------------------*;
* Ensmbl56: Producing Unformatted variable;
*------------------------------------------------------------*;
label U_DepVar = "Unnormalized Into: DepVar";
if I_DepVar = '1' then U_DepVar = 1;
else
if I_DepVar = '0' then U_DepVar = 0;
*------------------------------------------------------------*;
* Ensmbl56: Computing _WARN_ Variable;
*------------------------------------------------------------*;
length _WARN_ $4;
label _WARN_ = 'Warnings';
_WARN_ = '';
if index(AUTONEURAL36_WARN_, 'M') and ^index(_WARN_, 'M') then substr(_WARN_, 1, 1) ='M';
if index(AUTONEURAL36_WARN_, 'U') and ^index(_WARN_, 'U') then substr(_WARN_, 2, 1) ='U';
if index(AUTONEURAL36_WARN_, 'P') and ^index(_WARN_, 'P') then substr(_WARN_, 3, 1) ='P';
if index(AUTONEURAL36_WARN_, 'C') and ^index(_WARN_, 'C') then substr(_WARN_, 4, 1) ='C';
if index(AUTONEURAL35_WARN_, 'M') and ^index(_WARN_, 'M') then substr(_WARN_, 1, 1) ='M';
if index(AUTONEURAL35_WARN_, 'U') and ^index(_WARN_, 'U') then substr(_WARN_, 2, 1) ='U';
if index(AUTONEURAL35_WARN_, 'P') and ^index(_WARN_, 'P') then substr(_WARN_, 3, 1) ='P';
if index(AUTONEURAL35_WARN_, 'C') and ^index(_WARN_, 'C') then substr(_WARN_, 4, 1) ='C';
if index(AUTONEURAL34_WARN_, 'M') and ^index(_WARN_, 'M') then substr(_WARN_, 1, 1) ='M';
if index(AUTONEURAL34_WARN_, 'U') and ^index(_WARN_, 'U') then substr(_WARN_, 2, 1) ='U';
if index(AUTONEURAL34_WARN_, 'P') and ^index(_WARN_, 'P') then substr(_WARN_, 3, 1) ='P';
if index(AUTONEURAL34_WARN_, 'C') and ^index(_WARN_, 'C') then substr(_WARN_, 4, 1) ='C';
if index(AUTONEURAL40_WARN_, 'M') and ^index(_WARN_, 'M') then substr(_WARN_, 1, 1) ='M';
if index(AUTONEURAL40_WARN_, 'U') and ^index(_WARN_, 'U') then substr(_WARN_, 2, 1) ='U';
if index(AUTONEURAL40_WARN_, 'P') and ^index(_WARN_, 'P') then substr(_WARN_, 3, 1) ='P';
if index(AUTONEURAL40_WARN_, 'C') and ^index(_WARN_, 'C') then substr(_WARN_, 4, 1) ='C';
if index(AUTONEURAL39_WARN_, 'M') and ^index(_WARN_, 'M') then substr(_WARN_, 1, 1) ='M';
if index(AUTONEURAL39_WARN_, 'U') and ^index(_WARN_, 'U') then substr(_WARN_, 2, 1) ='U';
if index(AUTONEURAL39_WARN_, 'P') and ^index(_WARN_, 'P') then substr(_WARN_, 3, 1) ='P';
if index(AUTONEURAL39_WARN_, 'C') and ^index(_WARN_, 'C') then substr(_WARN_, 4, 1) ='C';
if index(AUTONEURAL38_WARN_, 'M') and ^index(_WARN_, 'M') then substr(_WARN_, 1, 1) ='M';
if index(AUTONEURAL38_WARN_, 'U') and ^index(_WARN_, 'U') then substr(_WARN_, 2, 1) ='U';
if index(AUTONEURAL38_WARN_, 'P') and ^index(_WARN_, 'P') then substr(_WARN_, 3, 1) ='P';
if index(AUTONEURAL38_WARN_, 'C') and ^index(_WARN_, 'C') then substr(_WARN_, 4, 1) ='C';
if index(AUTONEURAL37_WARN_, 'M') and ^index(_WARN_, 'M') then substr(_WARN_, 1, 1) ='M';
if index(AUTONEURAL37_WARN_, 'U') and ^index(_WARN_, 'U') then substr(_WARN_, 2, 1) ='U';
if index(AUTONEURAL37_WARN_, 'P') and ^index(_WARN_, 'P') then substr(_WARN_, 3, 1) ='P';
if index(AUTONEURAL37_WARN_, 'C') and ^index(_WARN_, 'C') then substr(_WARN_, 4, 1) ='C';
*------------------------------------------------------------*;
* Ensmbl56: Computing Residual Vars;
*------------------------------------------------------------*;
if
F_DepVar NE '1'
AND F_DepVar NE '0'
then do;
R_DepVar1 = .;
R_DepVar0 = .;
end;
else do;
R_DepVar1 = -P_DepVar1;
R_DepVar0 = -P_DepVar0;
SELECT(F_DepVar);
WHEN('1') R_DepVar1 = R_DepVar1 +1;
WHEN('0') R_DepVar0 = R_DepVar0 +1;
OTHERWISE;
END;
END;
