*------------------------------------------------------------*;
* Variable Attributes for DATA;
*------------------------------------------------------------*;
if upcase(NAME) = "ACCEPTEDCMP1" then NEWROLE="REJECTED";
if upcase(NAME) = "ACCEPTEDCMP2" then NEWROLE="REJECTED";
if upcase(NAME) = "ACCEPTEDCMP3" then NEWROLE="REJECTED";
if upcase(NAME) = "ACCEPTEDCMP4" then NEWROLE="REJECTED";
if upcase(NAME) = "ACCEPTEDCMP5" then NEWROLE="REJECTED";
if upcase(NAME) = "AGE" then NEWROLE="REJECTED";
if upcase(NAME) = "COMPLAIN" then NEWROLE="REJECTED";
if upcase(NAME) = "DT_CUSTOMER" then NEWROLE="REJECTED";
if upcase(NAME) = "EDUCATION" then NEWROLE="REJECTED";
if upcase(NAME) = "HIGHEREDUCATION" then NEWROLE="REJECTED";
if upcase(NAME) = "HIGHEREDUCATION" then HIDE="Y";
if upcase(NAME) = "HIGHEREDUCATIONBINARY" then NEWROLE="REJECTED";
if upcase(NAME) = "KIDHOME" then NEWROLE="REJECTED";
if upcase(NAME) = "MNTFISHPRODUCTS" then NEWROLE="REJECTED";
if upcase(NAME) = "MNTFRUITS" then NEWROLE="REJECTED";
if upcase(NAME) = "MNTSWEETPRODUCTS" then NEWROLE="REJECTED";
if upcase(NAME) = "MNTWINES" then NEWROLE="REJECTED";
if upcase(NAME) = "MONTHSASCUSTOMER" then NEWROLE="REJECTED";
if upcase(NAME) = "NUMDISTPURCHASES" then NEWROLE="REJECTED";
if upcase(NAME) = "NUMSTOREPURCHASES" then NEWROLE="REJECTED";
if upcase(NAME) = "NUMWEBPURCHASES" then NEWROLE="REJECTED";
if upcase(NAME) = "RMNTFRQ" then NEWROLE="REJECTED";
