if name='Age' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Age_Exmpl2' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='CatPurchase' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Clothes' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Dependents' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Education' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Frq' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Gender' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='HigherEducation' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='HouseKeeping' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Income' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Kitchen' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Marital_Status' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Mnt' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='MonthsAsCustomer' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='NetPurchase' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='RMntFrq' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='RMntFrq_Exmpl2' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Rcn' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Recomendation' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='SmallAppliances' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Toys' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
