if name='AcceptedCmp1' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='AcceptedCmp2' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='AcceptedCmp3' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='AcceptedCmp4' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='AcceptedCmp5' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='AcceptedCmpTotal' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Age' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Complain' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Education' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Frq' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='HigherEducationBinary' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Income' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Kidhome' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Marital_Status' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Mnt' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='MntFishProducts' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='MntFruits' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='MntGoldProds' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='MntMeatProducts' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='MntSweetProducts' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='MntWines' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='MonthsAsCustomer' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='NumCatalogPurchases' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='NumDealsPurchases' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='NumDistPurchases' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='NumStorePurchases' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='NumWebPurchases' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='NumWebVisitsMonth' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='RFMstat' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='RMntFrq' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Recency' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Teenhome' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='Year_Birth' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
